title: <p align="center"> Vinay Pai </p>
logo: /assets/img/logo.png
description: I am new to the world of AI and ML and also to Python. I hope to gain a deeper understanding of the underlying concepts of analytics to fully appreciate all the new perspectives one can gain by focussed data analysis.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
